Task 1/workenv init and graph utils
Kuarni/formal-lang-course pull request #1
Opened 2024-09-08 09:48 UTC by Kuarni

- [x] Сделать `fork` данного репозитория.
- [x] Добавить ссылку на ваш `fork` в [таблицу](https://docs.google.com/spreadsheets/d/1X7Hx6IyltD_NyTTphyzbN74Ag-G_LDzUu4OGcHoI8tg/edit?usp=sharing).
- [x] Добавить в совладельцы форка одного из ассистентов (чтобы узнать, кого именно, нужно посмотреть в таблицу)
- [x] Реализовать модуль, предоставляющий перечисленные ниже возможности. Для работы с графами использовать [cfpq-data](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/tutorial.html#graphs). Данный модуль в дальнейшем будет расширяться. Функции, которые необходимо реализовать:
  - [x] По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах. Для получения графа по имени использовать [эту функцию](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/tutorial.html#load-graph).
  - [x] По количеству вершин в циклах и именам меток строить [граф из двух циклов](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.generators.labeled_two_cycles_graph.html#cfpq_data.graphs.generators.labeled_two_cycles_graph) и сохранять его в указанный файл в формате DOT (использовать pydot).
- [x] Добавить необходимые тесты.

2024-09-11 14:31 UTC, vadyushkins requested changes

2024-09-11 14:31 UTC, vivalerievich commented on tests/test_task_1_graph_utils.py
> +"""
Вынесите в отдельный файл

2024-09-11 14:31 UTC, vivalerievich commented on tests/test_task_1_graph_utils.py
> +        pass
Для чего это тут?

2024-09-13 17:47 UTC, Kuarni commented on tests/test_task_1_graph_utils.py
> +        pass
Слепота на оба глаза, не увидел и не убрал

2024-09-17 13:30 UTC, vadyushkins approved these changes

2024-09-17 21:07 UTC, merged